### ISSUE TITLE
Add a user agent

### ISSUE THREAD

**Issue by Ironholds** [hdmetor/WikiCrawler#1]
On the subject of "please follow their rules", please add a descriptive user agent to this project.

**Comment by hdmetor** [comment]
Thanks for the suggestion. Please have a look at 

https://github.com/hdmetor/WikiCrawler/pull/3

and let me know if this can work

**Comment by Ironholds** [comment]
Suggest having the full URL (that is, http(s)://github.com/....) but other than that it looks great.

**Comment by hdmetor** [comment]
Done
